/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import pack.control.c_koneksi;
import pack.control.controllerToko;
import pack.model.m_toko;

/**
 *
 * @author Nugrahanto
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    controllerToko ctoko;
    List<m_toko>listdata = new ArrayList<>();
    
    public home() {
        initComponents();
        ctoko = new controllerToko(this);
        ctoko.isiTable();
        String user = null;
        t_admin.setText(user);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_admin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TxtKode = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CbJenis = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Btn_Simpan = new javax.swing.JButton();
        Btn_Ubah = new javax.swing.JButton();
        Btn_Clear = new javax.swing.JButton();
        Btn_Hapus = new javax.swing.JButton();
        Btn_Keluar = new javax.swing.JButton();
        CbKategori = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CbCariKategori = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Cookies", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA BARANG DI TOKO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 30, 230, 40);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cookies", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Toko");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(-10.0F);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 72, 14);

        t_admin.setEditable(false);
        t_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_adminActionPerformed(evt);
            }
        });
        jPanel1.add(t_admin);
        t_admin.setBounds(90, 13, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 90);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cookies", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kode Barang          :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 20, 180, 30);
        jPanel2.add(TxtKode);
        TxtKode.setBounds(200, 20, 270, 30);
        jPanel2.add(TxtNama);
        TxtNama.setBounds(200, 60, 270, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Cookies", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Barang          :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 60, 180, 30);
        jPanel2.add(TxtHarga);
        TxtHarga.setBounds(200, 180, 270, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Cookies", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga                      :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 180, 180, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Cookies", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kategori Barang   :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 100, 180, 30);

        CbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack", "Box" }));
        jPanel2.add(CbJenis);
        CbJenis.setBounds(200, 140, 270, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Cookies", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jenis Packaging    :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 140, 180, 30);

        Btn_Simpan.setText("SIMPAN");
        Btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SimpanActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Simpan);
        Btn_Simpan.setBounds(550, 20, 120, 30);

        Btn_Ubah.setText("UBAH");
        Btn_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UbahActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Ubah);
        Btn_Ubah.setBounds(550, 60, 120, 30);

        Btn_Clear.setText("BERSIHKAN");
        Btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClearActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Clear);
        Btn_Clear.setBounds(550, 100, 120, 30);

        Btn_Hapus.setText("HAPUS");
        Btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HapusActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Hapus);
        Btn_Hapus.setBounds(550, 140, 120, 30);

        Btn_Keluar.setText("KELUAR");
        Btn_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KeluarActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Keluar);
        Btn_Keluar.setBounds(550, 180, 120, 30);

        CbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Baranglain" }));
        CbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbKategoriActionPerformed(evt);
            }
        });
        jPanel2.add(CbKategori);
        CbKategori.setBounds(200, 100, 270, 30);

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pencarian Berdasarkan");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 20, 170, 30);

        jLabel9.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Kategori");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 40, 170, 30);

        CbCariKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Baranglain" }));
        CbCariKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbCariKategoriActionPerformed(evt);
            }
        });
        jPanel3.add(CbCariKategori);
        CbCariKategori.setBounds(40, 70, 110, 30);

        jButton6.setText("CARI");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(50, 110, 90, 30);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode barang", "Nama Barang", "Kategori", "Packaging", "Harga"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(200, 20, 510, 140);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 230, 730, 180);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 730, 410);

        setBounds(0, 0, 744, 534);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SimpanActionPerformed
        // TODO add your handling code here:
        ctoko.SimpanData();
        ctoko.isiTable();
    }//GEN-LAST:event_Btn_SimpanActionPerformed

    private void Btn_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UbahActionPerformed
        // TODO add your handling code here:
        ctoko.Ubah();
        ctoko.isiTable();
    }//GEN-LAST:event_Btn_UbahActionPerformed

    private void Btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClearActionPerformed
        // TODO add your handling code here:
        ctoko.Reset();
    }//GEN-LAST:event_Btn_ClearActionPerformed

    private void Btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HapusActionPerformed
        // TODO add your handling code here:
        ctoko.Hapus();
        ctoko.isiTable();
    }//GEN-LAST:event_Btn_HapusActionPerformed

    private void Btn_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Btn_KeluarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ctoko.CariKategori();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String user1 = login.user;
        t_admin.setText(user1);        
    }//GEN-LAST:event_formWindowOpened

    private void t_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_adminActionPerformed

    private void CbCariKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbCariKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbCariKategoriActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        ctoko.isiField(Table.getSelectedRow());
        
    }//GEN-LAST:event_TableMouseClicked

    private void CbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    
    public JTextField getTxtKode(){
    return TxtKode;
    }
    public JTextField getTxtNama(){
    return TxtNama;
    }
    public JTextField getTxtHarga(){
    return TxtHarga;
    }
    public JComboBox getCbKategori(){
    return CbKategori;
    }
    public JComboBox getCbJenis(){
    return CbJenis;
    }
    public JComboBox getCbCariKategori(){
    return CbCariKategori;
    }
    public JButton getButtonHapus(){
    return Btn_Hapus;
    }
    public JButton getButtonBersih(){
    return Btn_Clear;
    }
    public JButton getButtonSimpan(){
    return Btn_Simpan;
    }
    public JButton getButtonUbah(){
    return Btn_Ubah;
    }
    public JButton getButtonKeluar(){
    return Btn_Keluar;
    }
    public JTable getTableData(){
    return Table;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Clear;
    private javax.swing.JButton Btn_Hapus;
    private javax.swing.JButton Btn_Keluar;
    private javax.swing.JButton Btn_Simpan;
    private javax.swing.JButton Btn_Ubah;
    private javax.swing.JComboBox<String> CbCariKategori;
    private javax.swing.JComboBox<String> CbJenis;
    private javax.swing.JComboBox<String> CbKategori;
    private javax.swing.JTable Table;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtKode;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField t_admin;
    // End of variables declaration//GEN-END:variables
}
